#springdatasource.url= jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password= 3621
spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: 3621